package settings;

public enum Difficulty_Mode {
    ADDITION_LOW,
    ADDITION_MID,
    ADDITION_HIGH,

    SUBTRACTION_LOW,
    SUBTRACTION_MID,
    SUBTRACTION_HIGH,

    MULTIPLICATION_LOW,
    MULTIPLICATION_MID,
    MULTIPLICATION_HIGH,

    DIVISION_LOW,
    DIVISION_MID,
    DIVISION_HIGH,
}